AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: ''
Resources:
  MainVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: example

  # MainInternetGateway:
  #   Type: "AWS::EC2::InternetGateway"
  #   Properties:
  #     Tags:
  #       - Key: Name
  #         Value: example-internet

  # MainRoute:
  #   Type: "AWS::EC2::Route"
  #   Properties:

  #     DestinationCidrBlock: "0.0.0.0/0"
  #     DestinationIpv6CidrBlock: String
  #     GatewayId: String
  #     InstanceId: String
  #     NatGatewayId: String
  #     NetworkInterfaceId: String
  #     RoputeTableId: String

  # PublicBlueSubnet:
  #   Type: "AWS::EC2::Subnet"
  #   DependsOn: MainVPC
  #   Properties:
  #     VpcId:
  #       Ref: MainVPC
  #     AvailabilityZone: us-east-1a
  #     CidrBlock: 10.0.0.0/24
  #     Tags:
  #       - Key: Name
  #         Value: example-public-blue
